name: Test for Conventional Commits
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/conventional-commits.yml
      - .github/workflows/_internal-test-conventional-commits.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  exercise:
    name: Exercise
    uses: ./.github/workflows/conventional-commits.yml
    with:
      pr-number: "17" # Pull request for test
    permissions:
      contents: read
      pull-requests: write

  verify:
    name: Verify
    needs: [exercise]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CONFIGURATION_SHA256: ${{ needs.exercise.outputs.configuration-sha256 }}
    steps:
      - name: Verify
        run: |
          set -x
          test "${CONFIGURATION_SHA256}" = "c23781fa57155600a0ee8b159012354d1d586d1f2857ef73048a8546056d06e8"
