name: Test for Composite Action
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/composite-action.yml
      - .github/workflows/_internal-test-composite-action.yml

concurrency:
  group: composite-action-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  exercise:
    name: Exercise
    uses: ./.github/workflows/composite-action.yml
    with:
      pr-number: "17" # Pull request for test
    permissions:
      contents: read
      pull-requests: write

  verify:
    name: Verify
    needs: [exercise]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CONFIGURATION_SHA256: ${{ needs.exercise.outputs.configuration-sha256 }}
    steps:
      - name: Verify
        run: |
          set -x
          test "${CONFIGURATION_SHA256}" = "5299577caf56560581ca6515ee565572df6520c8e843de73e9dcde5d95d19865"
