name: Label Conventional Commits
on:
  workflow_call:
    inputs:
      pr-number:
        type: string
        required: false
        description: The pull request number(s).

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Cross Labeler
        uses: tmknom/cross-labeler-action@71badeae9778cb9bbba312f9e1c035bb0dff72c0 # v0.2.1
        with:
          pr-number: ${{ inputs.pr-number }}
          configuration-url: https://raw.githubusercontent.com/tmknom/configurations/v0.3.0/labeler/conventional-commits.yml
